### ISSUE TITLE
File sr_nfv_connector.box not found on http://cs.gssi.infn.it/files/SFC/ 

### ISSUE THREAD

**Issue by keesjank** [netgroup/SRv6-net-prog#1]
Hi,

It seems http://cs.gssi.infn.it/files/SFC/sr_nfv_connector.box is not available. It is used in the VNF example. Vagrant fails with an error:

```
ubuntu@blade04:~/SRv6-net-prog$ vagrant box add sr-vnf http://cs.gssi.infn.it/files/SFC/sr_nfv_connector.box==> box: Box file was not detected as metadata. Adding it directly...
==> box: Adding box 'sr-vnf' (v0) for provider: 
    box: Downloading: http://cs.gssi.infn.it/files/SFC/sr_nfv_connector.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
ubuntu@blade04:~/SRv6-net-prog$
```
Same error when using a web browser. Any suggestions what to do?

**Comment by ghost** [comment]
Hi, 
This vagrant box is not available anymore, I'm working on updating the repo with the newer testbed 
In the meanwhile you can use the following vagrant box: 

$ vagrant box add sr-vnf http://cs.gssi.infn.it/files/SFC/srv6-net-prog.box

This vagrant box has a linux kernel 4.10 
Please note that segment routing is not enabled by default in kernel 4.10, you need to change the procfs to enable it 
To enable Segment routing, you can use the following sysctl 
sysctl -w net.ipv6.conf.all.seg6_enabled=1
sysctl -w net.ipv6.conf.<dev>.seg6_enabled=1
where dev is an interface that is used to receive SRv6 traffic 
for example 
sysctl -w net.ipv6.conf.eth1.seg6_enabled=1

Soon we will update this repo with the latest version of code and testbed 
Regards  
Ahmed

**Comment by keesjank** [comment]
Ah great! I think your \<dev\> was regarded as markup or something, because it disappeared, but I'm familiar with the concept. There are several features that are configured like this. rpfilter is one I used before. Thanks!

**Comment by ghost** [comment]
You're welcome!

**Comment by Rikaa-ops** [comment]
Hi,

It seems http://cs.gssi.infn.it/files/SFC/srv6-net-prog.box is not available. It is used in the VNF example.
